server:
  port: 7159


spring:
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: failover:(tcp://192.168.136.6:61616,tcp://192.168.136.7:61616,tcp://192.168.136.8:61616)
    user: admin
    password: admin
    packages:
      #信任所有的包
      trust-all: true
    pool:
      enabled: true
      max-connections: 5
    in-memory: false





